### PR TITLE
New version with clean css 5.1.4

### PR DESCRIPTION
**Pull request by jakubpawlowicz**
Please do not merge yet.

@johannchopin - do you know why my yarn.lock diff is so big? I generated it using npm 7.13.0 under node 16.2.0.

### CODE REVIEW

**Comment by johannchopin** [comment]
@jakubpawlowicz Yes I build this project using yarn and not npm so could you use the `yarn add ...` command instead of `npm i ...`? If it's fine for you to use yarn instead of npm I will add a CONTRIBUTING file that specify it 👍

**Comment by jakubpawlowicz** [comment]
Gotcha. I'm fine with yarn. Let me redo the PR.

**Comment by jakubpawlowicz** [comment]
Should be fine now, can you check @johannchopin ?

**Review by johannchopin — APPROVED** [review]
CR ✅  Actually it's my fault I didn't notice that there was still a `package-lock` file 😓  Could you please remove it real quick before merging the PR?

**Comment by jakubpawlowicz** [comment]
All done.

**Pull request merged**
